FLOOR_NAMES = [
    'P7', 'P6', 'P5', 'P4', 'P3', 'P2', 'P1',
    'LG',
    'G',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '11',
    '12',
    '13',
    '14',

]

NUM_FLOORS = len(FLOOR_NAMES)

FLOOR_INDEX = {name: i for i, name in enumerate(FLOOR_NAMES)}


COMMON_FLOORS = {'P7', 'P6', 'P5', 'P4', 'P3', 'P2', 'P1', 'LG', 'G', '1', '14'}
COMMON_FLOOR_INDICES = {FLOOR_INDEX[f] for f in COMMON_FLOORS}


BANK_A_EXCLUSIVE = {'8', '9', '10', '11', '12', '13'}
BANK_A_FLOORS = COMMON_FLOORS | BANK_A_EXCLUSIVE
BANK_A_FLOOR_INDICES = {FLOOR_INDEX[f] for f in BANK_A_FLOORS}


BANK_B_EXCLUSIVE = {'2', '3', '4', '5', '6', '7'}
BANK_B_FLOORS = COMMON_FLOORS | BANK_B_EXCLUSIVE
BANK_B_FLOOR_INDICES = {FLOOR_INDEX[f] for f in BANK_B_FLOORS}


BANK_A_LIFT_NAMES = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
BANK_B_LIFT_NAMES = ['I', 'J', 'K', 'L', 'M', 'N', 'O', 'P']

NUM_LIFTS_PER_BANK = 8
MAX_CAPACITY = 20
SAFE_CAPACITY = 18


DOOR_OPEN_AVG = 10
DOOR_OPEN_MAX = 30
TRAVEL_TIME_PER_FLOOR = 1
DECELERATION_TIME = 2


MAX_POPULATION = 15000
MIN_POPULATION = 10000


SIM_TICK = 1

MEAN_WAIT_BOUND = 30
MAX_WAIT_BOUND = 120
PEAK_FLOOR_WAIT_BOUND = 40
FAIRNESS_GAP_BOUND = 30
PRIORITY_PICKUP_BOUND = 30
DIRECTION_REVERSAL_COOLDOWN = 6
ENERGY_BUDGET_PER_HOUR = 50000
MOVEMENT_BUDGET_PER_HOUR = 600
IDLE_HOME_COUNT = 2
ROLLING_WINDOW_TICKS = 900


STATE_DIM = (NUM_LIFTS_PER_BANK * (1 + 1 + 1 + 1 + NUM_FLOORS)
             + NUM_FLOORS * 3
             + NUM_FLOORS
             + 4)
ACTION_DIM = 4
GAMMA = 0.95
GAE_LAMBDA = 0.95
PPO_CLIP = 0.2
LEARNING_RATE = 5e-4
PPO_EPOCHS = 4
BATCH_SIZE = 128
